### PR TITLE
Site defaults supporting multisite

### LINKED ISSUE #289: SiteDefaults are not localizable
SiteDefault ("/seo-pro/site-defaults/edit") are NOT localizable.

Blueprint sets some of them (ie. Meta Title, Meta Description, Site Name) as such, but actually it's impossible to translate them.

Furthermore, the yaml file where this data is saved (at least according to the default of the seo-pro config) is located in /content/seo-pro.yaml. This effectively prevents the possibility of locating its content.

The file should be saved in a dedicated folder within `/content`, e.g. `/content/seo-pro/`, in which the file is saved in the different sites, e.g. `/content/seo-pro/default/seo-pro.yaml`, `/content/seo-pro/french/seo-pro.yaml`, `/content/seo-pro/german/seo-pro.yaml`...

The `SiteDefaults` class should therefore handle the "_cascade_" of the values starting from the "default" locale and adding/overwriting the values of the selected locale.

Finally, the form to use I think should be the one used eg. in `Globals`, where the field to select the `Site` is next to the "Save" button above the form, on the right.

### PR DESCRIPTION
**Pull request by mwagena**
With this PR support is being added for multisite.
Fallback is added when using a config file with path to the yaml file.

output paths will be ./content/seo/sitehandle/defaults.yaml

Closes #289.

### CODE REVIEW

**Comment by duncanmcclean** [comment]
This PR still looks like it's a work-in-progress (lots of tests are failing & there's probably more to it than changing the file paths).

Going to mark this as a draft for now.

**Comment by mwagena** [comment]
hi @duncanmcclean 
I'll have to look into the tests then, the change is doing it's work when i tested it out while saving the 'site defaults' from within statamic cp. Also it returns the right data in the html pages in for example the <title> tag.

**Comment by mwagena** [comment]
@duncanmcclean i have updated the code slightly to support older versions of Laravel, in my enthusiasm i forgot the config()->bool() and config()->string() methods were relatively new

**Comment by duncanmcclean** [comment]
The tests still seem to be failing, I'm afraid.

When this is ready for us to look at, feel free to mark it as "Ready for review".

**Comment by mwagena** [comment]
I have replaced the logic with regular php versions to support all Laravel versions, local tests ran OK.

**Comment by jesseleite** [comment]
Thanks @mwagena for your work on this! I actually have some in-progress stuff on this front, which handles schema, but I'm also working out the UI in the CP for localizable site defaults as well. Going to close this for now so that we don't introduce two ways of doing the same thing, but I wanted to say I appreciate your PR ❤️

**Comment by mwagena** [comment]
> Thanks @mwagena for your work on this! I actually have some in-progress stuff on this front, which handles schema, but I'm also working out the UI in the CP for localizable site defaults as well. Going to close this for now so that we don't introduce two ways of doing the same thing, but I wanted to say I appreciate your PR ❤️

out of curiosity, what's the expectation on releasing this?

**Comment by mwagena** [comment]
@jesseleite What's the estimated time of release of multisite support?

**Comment by duncanmcclean** [comment]
I don't think we have an ETA, sorry!

**Pull request closed without merging**
