### PR TITLE
Misc performance improvements

### PR DESCRIPTION
**Pull request by ryanmitchell**
On a project we are working on we noticed the `seo-pro.meta` was taking 260ms to process on the front end (according to debugger), which is a lot more than other partials.

The caching introduced in this PR dropped that down to 67ms without any breaking changes.

### CODE REVIEW

**Comment by jesseleite** [comment]
Rad. @ryanmitchell Should we just use blink instead of class properties in all cases?

I know we've had problems in the past with cached class properties in certain edge case situations where a long-running worker running. Don't remember the specifics of how that'd affect us here, but don't think Blink would hurt?

**Comment by ryanmitchell** [comment]
I've used blink on the fieldtypesz now. Is there a need to make the key unique to the fields? Could there be multiple different source/sourcefields on the same request?

**Comment by jackmcdade** [comment]
the queen likes to party

**Comment by jesseleite** [comment]
>Well done!

Team effort... @jasonvarga was quietly in here via 🍐 too!

**Pull request merged**
