### PR TITLE
Add support for passing meta into view data for custom routes

### LINKED ISSUE #254: Context not used when on an non-entry page
We have a Statamic route defined:

```php
    Route::statamic('search', 'simple::search', [
        'disable_header' => config('simple.search.disable_header', false),
        'disable_footer' => config('simple.search.disable_footer', false),
        'title' => 'Search',
    ]);
```

On that page the `title` in SEO Pro meta tag is not set properly, because it doesn't pull from the view's context.

PR incoming.

### PR DESCRIPTION
**Pull request by edalzell**
Closes #254

### CODE REVIEW

**Comment by edalzell** [comment]
Got a test in there @jesseleite, but it's failing because it's falling back to the home, which might be correct but not what I expected. Like that `canonical_url` is the home page, is that right in this case?

**Comment by jesseleite** [comment]
> it's falling back to the home, which might be correct but not what I expected

Yep, it's by design that we want to fall back to home page data by default, as that makes for better SEO than falling back to nothing. The above commits fix this to respect your current URL (ie. when using custom routes like you are) 👍

**Comment by jesseleite** [comment]
^ Would just like to work out blade layout component support before we merge this is all (see failing test).

**Comment by jesseleite** [comment]
^ Would just like to work out blade layout component support before we merge this is all (see failing test).

**Pull request merged**
