### PR TITLE
Add blade directive

### PR DESCRIPTION
**Pull request by Daynnnnn**
Adds a directive for use with blade. This seems to solve an issue we had where the context on the anters tag was showing as null when using `{!! tag('seo_pro:meta') !!}` - causing page specific overwrites not to show.

As far as changes to existing logic goes, I've:
- Moved meta html generation into a trait, so it can be used on both the antlers tag and blade directive.
- Updated tests to use a data provider, which runs tests against both the antlers tag and blade directive outputs.

### CODE REVIEW

**Comment by Christophvh** [comment]
Any news on merging this? Cant seem to get SEO working with blade.

**Comment by ryanmitchell** [comment]
I'm guessing this isn't needed now that 3.3 has Statamic::tag() support?

**Comment by Christophvh** [comment]
> Yeah you can pass context in with Statamic::tag(), which would solve the issue we had.
> 
> With this PR, you'd do: `@seo_pro('meta')`
> 
> With Statamic::tag(), you'd do: `Statamic::tag('seo_pro:meta')->context(get_defined_vars())`
> 
> This PRs way feels nicer, but I guess it's up to Statamic really if they think it's worth it 🤷‍♂️

yeah, PR is still useful, use @ is way more in line with other custom blade directives.

**Comment by jesseleite** [comment]
Just a note, if you're using the `Statamic::tag()` helper, we recommend passing `$__data` from the view data instead of `get_defined_vars()`.

Also, I simplified the implementation a bit by removing the `GetsOutputHTML` trait and having the blade directive extend the tags class.

Anyway, great PR thanks! Will be in next release 🤘

**Pull request merged**
